#!/usr/bin/env bash
set -euo pipefail

: "${PROJECT_ID:?Set PROJECT_ID}"
: "${GCS_BUCKET:?Set GCS_BUCKET}"
: "${ALLOWED_FIREBASE_UID:?Set ALLOWED_FIREBASE_UID}"

REGION="${REGION:-us-west1}"
VERTEX_LOCATION="${VERTEX_LOCATION:-global}"
GEMINI_MODEL="${GEMINI_MODEL:-gemini-3.6-flash}"
DAILY_DICTATION_LIMIT="${DAILY_DICTATION_LIMIT:-50}"
DAILY_AUDIO_BYTES_LIMIT="${DAILY_AUDIO_BYTES_LIMIT:-2147483648}"
DAILY_AUDIO_DURATION_MS_LIMIT="${DAILY_AUDIO_DURATION_MS_LIMIT:-43200000}"
DAILY_SPEECH_SUBMISSION_LIMIT="${DAILY_SPEECH_SUBMISSION_LIMIT:-75}"
DAILY_VERTEX_REQUEST_LIMIT="${DAILY_VERTEX_REQUEST_LIMIT:-200}"
SERVICE_ACCOUNT="chirp-api@${PROJECT_ID}.iam.gserviceaccount.com"
BUILD_SERVICE_ACCOUNT="chirp-build@${PROJECT_ID}.iam.gserviceaccount.com"
CLOUD_DIR="$(cd "$(dirname "$0")/.." && pwd)"

gcloud run deploy chirp-api \
  --source "$CLOUD_DIR" \
  --project "$PROJECT_ID" \
  --region "$REGION" \
  --service-account "$SERVICE_ACCOUNT" \
  --build-service-account="projects/${PROJECT_ID}/serviceAccounts/${BUILD_SERVICE_ACCOUNT}" \
  --allow-unauthenticated \
  --concurrency=20 \
  --cpu=1 \
  --memory=512Mi \
  --min-instances=0 \
  --max-instances=2 \
  --timeout=300s \
  --set-env-vars="GCP_PROJECT=$PROJECT_ID,GCS_BUCKET=$GCS_BUCKET,ALLOWED_FIREBASE_UID=$ALLOWED_FIREBASE_UID,SPEECH_LOCATION=us,VERTEX_ENABLED=true,VERTEX_LOCATION=$VERTEX_LOCATION,GEMINI_MODEL=$GEMINI_MODEL,DAILY_DICTATION_LIMIT=$DAILY_DICTATION_LIMIT,DAILY_AUDIO_BYTES_LIMIT=$DAILY_AUDIO_BYTES_LIMIT,DAILY_AUDIO_DURATION_MS_LIMIT=$DAILY_AUDIO_DURATION_MS_LIMIT,DAILY_SPEECH_SUBMISSION_LIMIT=$DAILY_SPEECH_SUBMISSION_LIMIT,DAILY_VERTEX_REQUEST_LIMIT=$DAILY_VERTEX_REQUEST_LIMIT"
