package dev.chirpboard.app.core.util

import java.text.SimpleDateFormat
import java.util.*
import kotlin.time.Duration
import kotlin.time.Duration.Companion.milliseconds

private val nowCalendar = object : ThreadLocal<Calendar>() {
    override fun initialValue() = Calendar.getInstance()
}
private val thenCalendar = object : ThreadLocal<Calendar>() {
    override fun initialValue() = Calendar.getInstance()
}
private val yesterdayCalendar = object : ThreadLocal<Calendar>() {
    override fun initialValue() = Calendar.getInstance()
}
private val monthDayFormat = object : ThreadLocal<SimpleDateFormat>() {
    override fun initialValue() = SimpleDateFormat("MMM d", Locale.getDefault())
}
private val monthDayYearFormat = object : ThreadLocal<SimpleDateFormat>() {
    override fun initialValue() = SimpleDateFormat("MMM d, yyyy", Locale.getDefault())
}
private val dateTimeFormat = object : ThreadLocal<SimpleDateFormat>() {
    override fun initialValue() = SimpleDateFormat("MMM d, yyyy 'at' h:mm a", Locale.getDefault())
}
private val timeFormat = object : ThreadLocal<SimpleDateFormat>() {
    override fun initialValue() = SimpleDateFormat("h:mm a", Locale.getDefault())
}

/**
 * Format duration as "MM:SS" or "HH:MM:SS" for longer durations.
 */
fun Duration.formatDuration(): String {
    val totalSeconds = inWholeSeconds
    val hours = totalSeconds / 3600
    val minutes = (totalSeconds % 3600) / 60
    val seconds = totalSeconds % 60
    
    return if (hours > 0) {
        String.format("%d:%02d:%02d", hours, minutes, seconds)
    } else {
        String.format("%d:%02d", minutes, seconds)
    }
}

/**
 * Format milliseconds as duration string.
 */
fun Long.formatAsDuration(): String = this.milliseconds.formatDuration()

/**
 * Format date relative to now (Today, Yesterday, or date).
 */
fun Date.formatRelative(): String {
    val now = nowCalendar.get()!!.apply { timeInMillis = System.currentTimeMillis() }
    val then = thenCalendar.get()!!.apply { time = this@formatRelative }
    
    return when {
        isSameDay(now, then) -> "Today"
        isYesterday(now, then) -> "Yesterday"
        isSameYear(now, then) -> monthDayFormat.get()!!.format(this)
        else -> monthDayYearFormat.get()!!.format(this)
    }
}

/**
 * Format date with time.
 */
fun Date.formatDateTime(): String {
    return dateTimeFormat.get()!!.format(this)
}

private fun isSameDay(cal1: Calendar, cal2: Calendar): Boolean {
    return cal1.get(Calendar.YEAR) == cal2.get(Calendar.YEAR) &&
           cal1.get(Calendar.DAY_OF_YEAR) == cal2.get(Calendar.DAY_OF_YEAR)
}

private fun isYesterday(now: Calendar, then: Calendar): Boolean {
    val yesterday = yesterdayCalendar.get()!!.apply {
        timeInMillis = now.timeInMillis
        add(Calendar.DAY_OF_YEAR, -1)
    }
    return isSameDay(yesterday, then)
}

private fun isSameYear(cal1: Calendar, cal2: Calendar): Boolean {
    return cal1.get(Calendar.YEAR) == cal2.get(Calendar.YEAR)
}

/**
 * Format date for header subtitle display.
 * Shows relative day + time: "Today at 10:30 AM", "Yesterday at 3:45 PM", "Jan 29 at 10:30 AM"
 */
fun Date.formatForHeader(): String {
    val now = nowCalendar.get()!!.apply { timeInMillis = System.currentTimeMillis() }
    val then = thenCalendar.get()!!.apply { time = this@formatForHeader }
    val timeStr = timeFormat.get()!!.format(this)
    
    return when {
        isSameDay(now, then) -> "Today at $timeStr"
        isYesterday(now, then) -> "Yesterday at $timeStr"
        isSameYear(now, then) -> "${monthDayFormat.get()!!.format(this)} at $timeStr"
        else -> "${monthDayYearFormat.get()!!.format(this)} at $timeStr"
    }
}

/**
 * Check if a title looks like a default date-based title (e.g., "Jan 29, 10:30 AM").
 * Default titles are generated by RecordingService using "MMM d, h:mm a" format.
 */
fun String.isDefaultDateTitle(): Boolean {
    // Pattern matches: "Jan 29, 10:30 AM" or similar date formats
    val datePattern = Regex("""^[A-Z][a-z]{2}\s+\d{1,2},?\s+\d{1,2}:\d{2}\s*[AaPp][Mm]$""")
    return datePattern.matches(this.trim())
}

/**
 * Truncate string with ellipsis if longer than maxLength.
 */
fun String.truncate(maxLength: Int): String {
    return if (length <= maxLength) this else "${take(maxLength - 1)}..."
}

/**
 * Capitalize first letter of each word.
 */
fun String.titleCase(): String {
    return split(" ").joinToString(" ") { word ->
        word.replaceFirstChar { if (it.isLowerCase()) it.titlecase(Locale.getDefault()) else it.toString() }
    }
}
